kiplot:
  version: 1

outputs:
# STEP (ISO 10303-21 Clear Text Encoding of the Exchange Structure):
  # This is the most common 3D format for exchange purposes.
  # This output is what you get from the 'File/Export/STEP' menu in pcbnew.
  - name: 'step_example'
    comment: 'Exports the PCB as a 3D model.'
    type: 'step'
#    dir: 'cad'
    options:
      # [boolean=true] use metric units instead of inches
      metric_units: true
      # [number=-1] the minimum distance between points to treat them as separate ones (-1 is KiCad default: 0.01 mm)
      min_distance: -1
      # [boolean=false] used to exclude 3D models for components with 'virtual' attribute
      no_virtual: false
      # [string='grid'] determines the coordinates origin. Using grid the coordinates are the same as you have in the design sheet.
      # The drill option uses the auxiliar reference defined by the user.
      # You can define any other origin using the format 'X,Y', i.e. '3.2,-10'
      origin: 'grid'
      # [string='%f-%i.%x'] name for the generated STEP file (%i='3D' %x='step') . Affected by global options
      output: '%f.%x'
