name: test

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    continue-on-error: false
    steps:
    - uses: actions/checkout@v2
    - name: kicad-exports docs
      uses: nerdyscout/kicad-exports:develop
      with:
        config: docs.kiplot.yaml
        dir: test
        board: test/test.kicad_pcb
        schema: test/test.sch
    - name: "check output: docs"
      run: |
        test -f test/docs/test-Schematic*.svg &&
        test -f test/docs/test-Schematic*.pdf && 
        test -f test/docs/test-Board*.pdf
    - uses: actions/upload-artifact@v2
      if: success()
      with:
        name: docs
        path: test/docs/*

  bom:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    - name: kicad-exports bom
      uses: nerdyscout/kicad-exports:develop
      with:
        config: bom.kiplot.yaml
        dir: test
        board: test/test.kicad_pcb
        schema: test/test.sch
    - name: "check output: bom"
      run: |
        test -f test/docs/bom/test*.html &&
        test -f test/docs/bom/test*.csv && 
        test -f test/docs/bom/test*.xlsx
    - uses: actions/upload-artifact@v2
      if: success()
      with:
        name: bom
        path: test/docs/bom/*

  fabrications:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    continue-on-error: false
    steps:
    - uses: actions/checkout@v2
    - name: kicad-exports fabrications 
      uses: nerdyscout/kicad-exports:develop
      with:
        config: fabrications.kiplot.yaml
        dir: test
        board: test/test.kicad_pcb
        schema: test/test.sch
    - name: "check output: fabrications"
      run: |
        test -f test/gerbers/testboth-pos.csv &&
        test -f test/gerbers/test-PTH.drl && 
        test -f test/gerbers/test-NPTH.drl
        test -f test/gerbers/test-Edge_Cuts.gbr &&
        test -f test/gerbers/test-F_Cu.gbr && 
        test -f test/gerbers/test-B_SilkS.gbr
    - uses: actions/upload-artifact@v2
      if: success()
      with:
        name: gerbers
        path: test/gerbers/*

  plot:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - name: kicad-exports plot
      uses: nerdyscout/kicad-exports:develop
      with:
        config: plot.kiplot.yaml
        dir: test
        schema: test/test.sch
        board: test/test.kicad_pcb
    - name: "check output: tracespace-board"
      run: |
        test -f test/docs/img/test_Board_Top.svg &&
        test -f test/docs/img/test_Board_Bottom.svg 
    - uses: actions/upload-artifact@v2
      if: success()
      with:
        name: img
        path: test/docs/img/*
